### ISSUE TITLE
GCP `deploymentId` saved to receipt file is incorrect

### ISSUE THREAD

**Issue by dcroote** [api3dao/airnode#1545] opened 2022-11-19 20:19 UTC
Using the latest master commit (technically I used `64cf03b5564cedfa362f2be3a4fe585cc9a01678`, but this includes the latest master `6b0ae76335793d9842d4caff14499449c5aaaf63`), deploying to GCP followed by running `remove-with-receipt` fails because the `deploymentId` stored in the `receipt.json` file (in this case `gcpc3579029`) is not the same as the one listed by the `info` command, which is `gcp5651a1ce`. Replacing the deploymentId in the `receipt.json` file then still fails unfortunately (last error below).

Deployment:
```sh
> docker run -it --rm   -e USER_ID=$(id -u) -e GROUP_ID=$(id -g)   -v "$(pwd):/app/config"   api3/airnode-deployer-dev:64cf03b5564cedfa362f2be3a4fe585cc9a01678 deploy
  ___  _                      _
 / _ \(_)                    | |
/ /_\ \_ _ __ _ __   ___   __| | ___
|  _  | | '__| '_ \ / _ \ / _` |/ _ \
| | | | | |  | | | | (_) | (_| |  __/
\_| |_/_|_|  |_| |_|\___/ \__,_|\___|

          Airnode v0.9.0

✔ Deployed Airnode 0x9E621805cadABCe2ab4cA6b4E0fceec32aC67785 tutorial-gcp to gcp us-east1
ℹ Outputted config/receipt.json
  This file does not contain any sensitive information.
```

Receipt file (abridged):
```json
{
  "deployment": {
    "deploymentId": "gcpc3579029",
    "cloudProvider": {
      "type": "gcp",
      "disableConcurrencyReservations": false
    },
    "stage": "tutorial-gcp",
    "nodeVersion": "0.9.0",
    "timestamp": "2022-11-19T19:18:44.707Z"
  },
  "success": true
}
```

Failure to remove:
```sh
> docker run -it --rm   -e USER_ID=$(id -u) -e GROUP_ID=$(id -g)   -v "$(pwd):/app/config"   api3/airnode-deployer-dev:64cf03b5564cedfa362f2be3a4fe585cc9a01678 remove-with-receipt
  ___  _                      _
 / _ \(_)                    | |
/ /_\ \_ _ __ _ __   ___   __| | ___
|  _  | | '__| '_ \ / _ \ / _` |/ _ \
| | | | | |  | | | | (_) | (_| |  __/
\_| |_/_|_|  |_| |_|\___/ \__,_|\___|

          Airnode v0.9.0

✖ Failed to remove Airnode 'gcpc3579029'



Error details:
✖ No deployment with ID 'gcpc3579029' found
```

The `info` command showing a different deployment ID:
```sh
> docker run -it --rm   -e USER_ID=$(id -u) -e GROUP_ID=$(id -g)   -v "$(pwd):/app/config"   api3/airnode-deployer-dev:64cf03b5564cedfa362f2be3a4fe585cc9a01678 list
✖ Failed to fetch deployments from AWS: Error: Failed to list S3 buckets: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
✔ Listing Airnode deployments from cloud provider GCP
┌───────────────┬────────────────┬───────────────────┬──────────────┬─────────────────┬─────────────────────────┐
│ Deployment ID │ Cloud provider │ Airnode address   │ Stage        │ Airnode version │ Last update             │
├───────────────┼────────────────┼───────────────────┼──────────────┼─────────────────┼─────────────────────────┤
│ gcp5651a1ce   │ GCP (us-east1) │ 0x9E6218...C67785 │ tutorial-gcp │ 0.9.0           │ 2022-11-19 19:18:44 UTC │
└───────────────┴────────────────┴───────────────────┴──────────────┴─────────────────┴─────────────────────────┘
```

After replacing deployment ID, removal still fails:
```sh
> docker run -it --rm   -e USER_ID=$(id -u) -e GROUP_ID=$(id -g)   -v "$(pwd):/app/config"   api3/airnode-deployer-dev:64cf03b5564cedfa362f2be3a4fe585cc9a01678 remove-with-receipt
  ___  _                      _
 / _ \(_)                    | |
/ /_\ \_ _ __ _ __   ___   __| | ___
|  _  | | '__| '_ \ / _ \ / _` |/ _ \
| | | | | |  | | | | (_) | (_| |  __/
\_| |_/_|_|  |_| |_|\___/ \__,_|\___|

          Airnode v0.9.0

ℹ Removing Airnode 'gcp5651a1ce'
✖ Error: Command failed: terraform destroy -var="gcp_region=us-east1" -var="gcp_project=${PROJECT_ID}" <redacted>

Error: no project value set. `project_id` must be set at the resource level, or a default `project` value must be specified on the provider

  with module.run.data.google_project.project,
  on ../../usr/local/share/.config/yarn/global/node_modules/@api3/airnode-deployer/dist/terraform/gcp/modules/function/data.tf line 1, in data "google_project" "project":
   1: data "google_project" "project" {


✖ Failed to remove Airnode 'gcp5651a1ce'
```

**Comment by Siegrift** [comment] 2022-11-19 20:22
Mhh, I suspect it fails also when you try the `remove` command with the deployment ID from `list`, right?

**Comment by dcroote** [comment] 2022-11-19 20:25
> Mhh, I suspect it fails also when you try the `remove` command with the deployment ID from `list`, right?

Unfortunately still the same error when using `remove` with the deployment ID from the `info` command: 
```
> docker run -it --rm   -e USER_ID=$(id -u) -e GROUP_ID=$(id -g)   -v "$(pwd):/app/config"   api3/airnode-deployer-dev:64cf03b5564cedfa362f2be3a4fe585cc9a01678 remove gcp5651a1ce

...same as above error...

Error: no project value set. `project_id` must be set at the resource level, or a default `project` value must be specified on the provider
```

**Comment by dcroote** [comment] 2022-11-20 01:17
I'm thinking the first issue might have to do with use of `hashDeployment` and `hashDeploymentVersion`, the latter which incorporates a `timestamp` and the former which does not. The former is used when writing to `receipt.json`:

https://github.com/api3dao/airnode/blob/6b0ae76335793d9842d4caff14499449c5aaaf63/packages/airnode-deployer/src/utils/files.ts#L33

**Comment by amarthadan** [comment] 2022-11-21 08:42
It took me a while but I see now what the problem is :sweat_smile:

You're interpolating GCP project ID from secrets and I don't do that when constructing the deployment ID. It's done correctly for `receipt.json` because the config is interpolated when deploying. But for `list` command it tries to hash `${PROJECT_ID}` instead of its value and produces a different deployment ID.
That's also why you can't remove the Airnode with `receipt.json`. The deployment ID there is correct but the instance is not found in the cloud because the ones generated from those in the cloud are incorrect.

Nice catch though! :slightly_smiling_face:  I'm going to close this issue (as the description is a bit misleading, more of a symptom than an actual issue) and I'll create a new one specifically for this bug.
https://github.com/api3dao/airnode/issues/1546

**Closed by amarthadan** 2022-11-21 08:42 UTC
Labels: airnode-deployer CLI
