### ISSUE TITLE
Research (and implement if possible) enabling CORS on the HTTP gateways

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1200] opened 2022-06-13 08:28 UTC
[Slack discussion](https://api3workspace.slack.com/archives/C02R79STBRA/p1646325797158989)
Should be configurable.

**Comment by vponline** [comment] 2022-07-26 06:55
Moving to blocked until I get some feedback since this is not directly doable for GCP, but could be achieved with the following workarounds:

1. Enabling a load balancer that will allow adding custom headers (https://cloud.google.com/load-balancing/docs/https/custom-headers)
2. Handling the pre-flight checks with an if-check inline (e.g. if (req.method === 'OPTIONS')... https://cloud.google.com/functions/docs/samples/functions-http-cors#functions_http_cors-nodejs)
3. Adding options methods to all paths for CORS requests: https://stackoverflow.com/a/65738206
4. Enable CORS for the Google Endpoints service (it turns out that API Gateway uses this behind the scenes: https://stackoverflow.com/a/67678657). We'd need to define either OpenAPI or gRPC: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/endpoints_service

**Comment by vponline** [comment] 2022-08-02 10:56
It was decided ([slack](https://api3workspace.slack.com/archives/C02AYRX8D89/p1658818358934319)) to implement options 2. + 3. for both AWS and GCP to keep the handling similar for both.

**Closed** 2022-08-04 08:47 UTC
Labels: needs documentation

**Comment by vponline** [comment] 2022-08-04 10:01
@kolenic-martin To test this you can go ahead and do a deployment with the `http` and `http-signed` gateways to both AWS and GCP and then make the POST request from a browser (like react) application, e.g. with fetch:

```
const res = await fetch(
        '<GATEWAY_URL>/<ENDPOINT_ID>',
        {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': '<API_KEY>',
            },
            body: JSON.stringify({ parameters: { coinIds: 'api3', coinVs_currencies: 'usd' } }),
        },
    );
```

**Comment by kolenic-martin** [comment] 2022-08-08 18:57
Hi @vponline, my testing strategy was basically doing what you suggested but used Postman to perform that request. It was a total of four tests:

1. GCP + http
2. GCP + signed
3. AWS + http
4. AWS + signed

I did not run into any problems and all of the requests were successful.

**Comment by vponline** [comment] 2022-08-09 06:08
@kolenic-martin Ok, just to confirm were you able to make a CORS request with Postman?

**Comment by kolenic-martin** [comment] 2022-08-09 06:38
You are right, this was probably not a CORS request that I attempted to
perform. I'm looking into it (reading Postman docs and Stackexchange) and
it might be easier with Curl but I need to read a little more. It should
not take too long though.

**Comment by vponline** [comment] 2022-08-09 07:37
Thanks @kolenic-martin! Let me know if you need help, I think using a template [React app](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) would be the fastest for you to test, though :smile: 

As an additional request, could you also confirm that the API Key authentication is still working (by testing that you are unable to make a POST request with an incorrect API Key value as there were some changes to the configuration of it as well.

**Comment by Siegrift** [comment] 2022-08-09 08:07
You need to make the request from **browser**, not curl or postman. You don't need a react application to test this tough. All you need is a single html and JS file

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    hello
  </body>
  <script src="./main.js"></script>
</html>
```

and

```
var myHeaders = new Headers()
myHeaders.append('x-api-key', '329b1851-eda2-41d0-9f5f-6db0bcc257c2')
myHeaders.append('Content-Type', 'application/json')

var raw = JSON.stringify({
  encodedParameters:
    '0x3173000000000000000000000000000000000000000000000000000000000000636f696e49640000000000000000000000000000000000000000000000000000626974636f696e00000000000000000000000000000000000000000000000000',
  x: 10,
})

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  body: raw,
  redirect: 'follow',
}

fetch(
  'http://localhost:3000/http-signed-data/0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4',
  requestOptions,
)
  .then((response) => response.text())
  .then((result) => console.log(result))
  .catch((error) => console.log(error))
```

You can get the JS implementation from postman (so just copy pasting is enough)

**Comment by kolenic-martin** [comment] 2022-08-12 06:52
Hi everyone, I just wanted to confirm that this works as intended. It fails if the API key of the deployment or endpoint IDs do not match, but that is expected behaviour.
