### ISSUE TITLE
Line endings in environment variable files lead to errors

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/airnode#1634] opened 2023-02-04 03:15 UTC
## Description

When using "CRLF" in `secrets.env` it leads to airnode not being able to parse the secrets.env and thowing an error.

## Version

Airnode Version 0.9.2

## Present Behaviour

Line endings like "CRLF" cause errors in parsing environment variable files

## Expected Behaviour

Line endings should not have an effect on environment variable files

### With "CRLF" 
![image](https://user-images.githubusercontent.com/31223740/216744670-808ff301-4b7f-4c62-a342-c8ed61176a46.png)

### With "LF"
![image](https://user-images.githubusercontent.com/31223740/216744939-3f867426-707a-41b0-acc0-696904526ed6.png)
![image](https://user-images.githubusercontent.com/31223740/216744989-b32990d4-12d3-4bf3-9032-6ebae35a05fc.png)

**Comment by dcroote** [comment] 2023-02-12 20:55
I'm using `v0.9.2` of `airnode-client` on Windows with `cmd` and I've been unable to reproduce this. I've tried `CRLF` line endings in `secrets.env` alone and in `config.json`, with and without quotations around the mnemonic, multiple lines between variables, and even tried weird attempts at pasting between LF and CRLF files. Each time I perform a http gateway request and wait for a complete coordinator cycle (which is where the issue occurred before per the screenshot above). I've also independently tested CRLF files with `dotenv` and unsurprisingly that is fine.

@Ashar2shahid you said you'd run into this before? Do you have more details or a reproducible workflow?

**Comment by Ashar2shahid** [comment] 2023-02-22 14:55
Hey @dcroote sure, so I've ran into this issue before when using WSL. I identified it was related to line endings because I constantly move files between WSL and windows (probably something you shouldn't do) and then configs that used to work before would stop working, changing the line endings to "LF" fixed these issues when running the deploy command from within WSL. Maybe reproducing this issue in Linux would be possible if WSL is not available

**Comment by dcroote** [comment] 2023-03-08 07:14
Thanks @Ashar2shahid but after yet more attempts I've still been unable to reproduce this. I've changed line endings to CRLF for all deployment files (`secrets.env`, `aws.env`, `config.json`), then used WSL to deploy  as you suggested. I deployed to AWS and separately ran the local container with no issues.

Do you have a set of specific steps I can follow to recreate the issue?

**Comment by dcroote** [comment] 2023-09-13 06:29
Closing as unable to be reproduced. This can always be reopened with a reproducible example or a user reported error.

**Closed by dcroote** 2023-09-13 06:29 UTC
