### ISSUE TITLE
"Can't access storage bucket deploying Airnode on GCP"

### ISSUE THREAD

**Issue by 37Rb** [api3dao/airnode#1313] opened 2022-07-05 14:01 UTC
## Description

I configured an Airnode with ChainAPI and am trying to deploy it on GCP. When I run the deploy command it fails with

```
2022-07-05T13:51:22.017Z ✖ Airnode deployment failed due to unexpected errors.
  It is possible that some resources have been deployed on cloud provider.
  Please use the "remove" command from the deployer CLI to ensure all cloud resources are removed.
2022-07-05T13:51:22.018Z ✖ admin-288@gcp-deploy-test-355413.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

## Version

Airnode Deployer docker image 0.6.4

## Steps to reproduce

1. Create a new GCP project
2. Enable the App Engine Admin API
3. Create a new service account with the Owner role
4. Create a key for the service account, download it and save it as gcp.json
5. Run the command given by ChainAPI

<img width="1433" alt="GCP Deploy 1" src="https://user-images.githubusercontent.com/82692355/177345149-2b83a893-9e3e-450f-98a8-ecb43187d5a3.png">

<img width="1574" alt="GCP Deploy 2" src="https://user-images.githubusercontent.com/82692355/177345218-d29f329b-3c71-449c-a54a-efdc9de0e3be.png">

<img width="1722" alt="GCP Deploy 3" src="https://user-images.githubusercontent.com/82692355/177345258-290bd667-fa15-41dc-8b24-ba9f42f2fe1d.png">

<img width="1737" alt="GCP Deploy 4" src="https://user-images.githubusercontent.com/82692355/177345302-f76c5f43-a001-44b9-9d4e-9f4e992f8c57.png">

```
$ docker run -it --rm -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd)/gcp.json:/app/gcp.json" -v "$(pwd)/config:/app/config" -v "$(pwd)/output:/app/output" api3/airnode-deployer:0.6.4 deploy --debug
  ___  _                      _      
 / _ \(_)                    | |     
/ /_\ \_ _ __ _ __   ___   __| | ___ 
|  _  | | '__| '_ \ / _ \ / _` |/ _ \
| | | | | |  | | | | (_) | (_| |  __/
\_| |_/_|_|  |_| |_|\___/ \__,_|\___|

          Airnode v0.6.4
        Deployer CLI v0.6.4

2022-07-05T13:51:20.934Z ℹ Running command deploy with arguments {"debug":true,"configuration":"config/config.json","config":"config/config.json","conf":"config/config.json","secrets":"config/secrets.env","receipt":"output/receipt.json"}
2022-07-05T13:51:20.935Z ℹ Parsing secrets file
2022-07-05T13:51:20.953Z ℹ Validating mnemonic
2022-07-05T13:51:21.341Z ℹ Creating a temporary secrets.json file
2022-07-05T13:51:21.349Z ℹ Deriving airnode wallet from mnemonic
2022-07-05T13:51:21.447Z ℹ Shortening Airnode Address
2022-07-05T13:51:21.463Z ℹ Deploying Airnode ea094b2 coingecko-1 to gcp us-central1
2022-07-05T13:51:21.465Z ℹ Checking Terraform state existence in GCP
2022-07-05T13:51:21.899Z ✖ Failed deploying Airnode ea094b2 coingecko-1 to gcp us-central1
2022-07-05T13:51:21.899Z ℹ Deleting a temporary secrets.json file
2022-07-05T13:51:21.903Z ℹ Deriving airnode wallet from mnemonic
2022-07-05T13:51:21.994Z ℹ Shortening Airnode Address
2022-07-05T13:51:21.996Z ℹ Deriving Airnode xpub from mnemonic
2022-07-05T13:51:22.012Z ℹ Writing receipt.json file
2022-07-05T13:51:22.016Z ℹ Outputted output/receipt.json
  This file does not contain any sensitive information.
2022-07-05T13:51:22.017Z ✖ Airnode deployment failed due to unexpected errors.
  It is possible that some resources have been deployed on cloud provider.
  Please use the "remove" command from the deployer CLI to ensure all cloud resources are removed.
2022-07-05T13:51:22.018Z ✖ admin-288@gcp-deploy-test-355413.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

**Comment by amarthadan** [comment] 2022-07-05 14:08
Can you also provide the `config.json` file?

**Comment by 37Rb** [comment] 2022-07-05 14:18
Yes sir.

```json
{
  "apiCredentials": [],
  "chains": [
    {
      "authorizers": [
        "0xf18c105D0375E80980e4EED829a4A68A539E6178"
      ],
      "blockHistoryLimit": 300,
      "contracts": {
        "AirnodeRrp": "0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd"
      },
      "id": "5",
      "ignoreBlockedRequestsAfterBlocks": 20,
      "maxConcurrency": 50,
      "minConfirmations": 0,
      "options": {
        "baseFeeMultiplier": 2,
        "fulfillmentGasLimit": 500000,
        "priorityFee": {
          "unit": "gwei",
          "value": 3.12
        },
        "txType": "eip1559"
      },
      "providers": {
        "goerli1": {
          "url": "${GOERLI_1_PROVIDER_URL}"
        },
        "goerli2": {
          "url": "${GOERLI_2_PROVIDER_URL}"
        },
        "goerli3": {
          "url": "${GOERLI_3_PROVIDER_URL}"
        }
      },
      "type": "evm"
    }
  ],
  "nodeSettings": {
    "airnodeWalletMnemonic": "${AIRNODE_WALLET_MNEMONIC}",
    "cloudProvider": {
      "disableConcurrencyReservations": true,
      "projectId": "${GCP_PROJECT_ID}",
      "region": "us-central1",
      "type": "gcp"
    },
    "heartbeat": {
      "apiKey": "${HEARTBEAT_API_KEY}",
      "enabled": true,
      "id": "${HEARTBEAT_ID}",
      "url": "${HEARTBEAT_URL}"
    },
    "httpGateway": {
      "apiKey": "${HTTP_GATEWAY_API_KEY_BETWEEN_30_TO_120_CHARACTERS}",
      "enabled": true,
      "maxConcurrency": 20
    },
    "httpSignedDataGateway": {
      "apiKey": "${HTTP_SIGNED_DATA_GATEWAY_API_KEY}",
      "enabled": true,
      "maxConcurrency": 20
    },
    "logFormat": "plain",
    "logLevel": "INFO",
    "nodeVersion": "0.6.4",
    "stage": "coingecko-1"
  },
  "ois": [
    {
      "apiSpecifications": {
        "components": {
          "securitySchemes": {}
        },
        "paths": {
          "/coins/{id}": {
            "get": {
              "parameters": [
                {
                  "in": "path",
                  "name": "id"
                }
              ]
            }
          }
        },
        "security": {},
        "servers": [
          {
            "url": "https://api.coingecko.com/api/v3"
          }
        ]
      },
      "endpoints": [
        {
          "fixedOperationParameters": [],
          "name": "GET_/coins/{id}",
          "operation": {
            "method": "get",
            "path": "/coins/{id}"
          },
          "parameters": [
            {
              "name": "id",
              "operationParameter": {
                "in": "path",
                "name": "id"
              }
            }
          ],
          "reservedParameters": [
            {
              "name": "_type"
            },
            {
              "name": "_path"
            },
            {
              "name": "_times"
            }
          ]
        }
      ],
      "oisFormat": "1.0.0",
      "title": "CoinGecko Coins by ID",
      "version": "0.1.0"
    }
  ],
  "triggers": {
    "http": [
      {
        "endpointId": "0xc5cec5f0dcd8638540c0aa716ddc4da017007b3507b842b8d428ce89b082d935",
        "endpointName": "GET_/coins/{id}",
        "oisTitle": "CoinGecko Coins by ID"
      }
    ],
    "httpSignedData": [
      {
        "endpointId": "0xc5cec5f0dcd8638540c0aa716ddc4da017007b3507b842b8d428ce89b082d935",
        "endpointName": "GET_/coins/{id}",
        "oisTitle": "CoinGecko Coins by ID"
      }
    ],
    "rrp": [
      {
        "endpointId": "0xc5cec5f0dcd8638540c0aa716ddc4da017007b3507b842b8d428ce89b082d935",
        "endpointName": "GET_/coins/{id}",
        "oisTitle": "CoinGecko Coins by ID"
      }
    ]
  }
}

```

**Comment by wkande** [comment] 2022-07-05 17:19
Just a shot in the dark. Has billing been enabled for the GCP project? See [here](https://docs.api3.org/airnode/v0.6/grp-providers/tutorial/quick-deploy-gcp/#gcp-project-setup-credentials). I recall having such an issue before related to billing.

**Comment by 37Rb** [comment] 2022-07-06 02:34
Yes, as far as I can tell billing is enabled. I have a billing account with a CC and it's linked to the project.

<img width="1051" alt="Screen Shot 2022-07-05 at 9 32 01 PM" src="https://user-images.githubusercontent.com/82692355/177455535-f4943a20-8d6c-479e-b99a-95008bf57a3a.png">

**Comment by Siegrift** [comment] 2022-07-06 09:05
> can you try enclosing everything in your secrets.env file in ""? Doing this yesterday fixed my GCP deployment.

That should not be required. I'm regularly deploying to GCP without the quoted secrets. Can you provide more info? I'd like to reproduce/fix this.

**Comment by bbenligiray** [comment] 2022-07-06 09:24
I used the ops repo to create configs, GCP wasn't deploying and I was in a rush to make it work and I did. It felt like it was enclosing things in quotations, specifically the project ID that did the trick, but I can't be sure.

**Comment by dcroote** [comment] 2022-07-10 17:01
I wonder if it has to do with [global uniqueness of bucket names](https://stackoverflow.com/a/63838860/6258652). Have you run the `remove` command (or [performed manual removal](https://docs.api3.org/airnode/v0.6/grp-providers/docker/deployer-image.html#gcp-3)) and confirmed that there aren't remaining storage buckets before retrying?

**Comment by bbenligiray** [comment] 2022-07-11 12:05
If it's the above, changing `stage` should also help

**Comment by bbenligiray** [comment] 2022-07-18 13:26
I've verified that [this](https://github.com/api3dao/airnode/issues/1313#issuecomment-1180327151) solves the problem. However, I suspect that [this](https://github.com/api3dao/airnode/issues/1313#issuecomment-1179763639) is not entirely what the issue is about.
I first deployed with the same configuration files that an API provider has already deployed with, and got `deployer@gcp-test-356713.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.` Then I modified `stage` and redeployed, which went through.
This is weird because [the bucket name is composed of the short Airnode address and `stage`](https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/terraform/state/gcp/main.tf#L2), and since the wallet mnemonics and Airnode addresses are different, there should have been no collision.

**Comment by vponline** [comment] 2022-07-23 08:57
I have tried to reproduce this error with new projects, different service accounts, configs, deployer versions (incl. 0.6.4) and different combinations of these.

The only way I get the same error is by using the above `config.json`, including the same stage (`coingecko-1`).

```
✖ Failed deploying Airnode e9953db coingecko-1 to gcp us-east1
ℹ Outputted output/receipt.json
  This file does not contain any sensitive information.
✖ Airnode deployment failed due to unexpected errors.
  It is possible that some resources have been deployed on cloud provider.
  Please use the "remove" command from the deployer CLI to ensure all cloud resources are removed.
✖ vp-service-3@vp-airnode-test-3.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

Changing the `stage` to something else (.e.g `coingecko-vp1`) results in a successful deployment.

**Comment by vponline** [comment] 2022-07-23 09:17
The google docs [say the following:](https://cloud.google.com/storage/docs/naming-buckets#considerations)

```
If you delete the project that contains the bucket, which effectively deletes the bucket as well, the bucket name may not be released for weeks or longer.
```

If I try to go create buckets with the same bucket names as projects that I've created and 'shut down' in the console yesterday, the UI tells me that the bucket names are not available. 


![Image](https://user-images.githubusercontent.com/65347007/180598893-929c2f45-16e6-49dd-8a9b-6b1c47485279.png)

**Comment by vponline** [comment] 2022-08-22 08:34
To summarize this issue, the root cause for the error was a storage bucket name collision. To mitigate this issue in the future, new patch versions, [0.6.6](https://github.com/api3dao/airnode/releases/tag/v0.6.6) and [0.7.3](https://github.com/api3dao/airnode/releases/tag/v0.7.3), were released.

The patches fix an issue where removing one of multiple deployments within one GCP project resulted in a removal error and the breaking of both deployments. Due to the error, the removal for either deployment was not completed and some resources remained (mainly the Terraform state bucket) which could lead to storage bucket name collision errors when attempting a new deployment with the same `config.json` (if attempting to use the same `stage`). Also to note, when shutting down a GCP project, any remaining storage buckets can remain [reserved for several weeks](https://cloud.google.com/storage/docs/naming-buckets#considerations) so shutting down the project is not a solution either. If experiencing removal errors, it is recommended to check and remove all remaining resources manually (please see the [docs](https://docs.api3.org/airnode/v0.6/grp-providers/docker/deployer-image.html#manual-removal) for details).

In addition, it is recommended to always use a unique stage, e.g. by including a timestamp such as  `yymmdd-hhmm` in the stage).

Two additional issues were discovered and resolved while investigating:

1. Not all GCP regions supporting all of the needed resources (e.g. App Engine) preventing deployments, resolved in [1380](https://github.com/api3dao/airnode/issues/1380)
2. A Terraform setting which caused problems when multiple Airnodes were deployed to the same project, resolved in [1349](https://github.com/api3dao/airnode/pull/1349)

In addition, there may be further changes to the naming of cloud resources if further changes are deemed necessary. Also, more detailed instructions regarding supported regions will be added to the documentation.

**Closed** 2022-08-22 08:37 UTC

**Comment by kolenic-martin** [comment] 2022-08-25 07:45
Hi @vponline; I am currently writing down a report on the regions that have all the necessary resources to successfully deploy and run the Airnode; in the meantime, I tested the Docker images of the versions you mention and the deployments seem to function properly; this also goes for the latest patches (v0.6.7 and v 0.7.5).
