### ISSUE TITLE
Implement gas price oracle

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1210] opened 2022-06-13 10:51 UTC
Same way as implemented in [Airseeker](https://github.com/api3dao/airseeker/blob/main/src/gas-oracle.ts)
We have to wait for https://api3dao.atlassian.net/browse/BEC-486 with this and then pretty much just reuse the implementation.

**Comment by amarthadan** [comment] 2022-06-22 12:30
@bbenligiray @aquarat Can we plan this soonish for Airseeker so it can be then ported to Airnode?

**Comment by bbenligiray** [comment] 2022-06-22 12:37
The new version of Airseeker has been running for ~10 days now and based on Ugur's Dune charts (https://dune.com/um61/API3-Requests and https://dune.com/um61/dapi-server-bnb) it seems to work fine. So we can go ahead with this.

**Comment by amarthadan** [comment] 2022-06-22 12:57
@bbenligiray But this is waiting for https://api3dao.atlassian.net/browse/BEC-486, implementation of gas price oracle strategies. That's what I meant that should be planned for Airseeker.

**Comment by bbenligiray** [comment] 2022-06-22 12:59
By plan you mean moving it to the board on the weekly call? Btw I'm not sure that this needs to happen on Airseeker first, then Airnode. Maybe it should be implemented in Airnode directly, then Airseeker can import and use it?

**Comment by amarthadan** [comment] 2022-06-29 12:16
Just to clarify, the plan is to implement the gas price oracle the same way as it is in Airseeker plus to implement the oracle strategies described in https://api3dao.atlassian.net/browse/BEC-486.

**Comment by vponline** [comment] 2022-07-08 06:43
I have encountered a problem with the CI blockchain's localhost network where the utilities e2e tests are not passing yet, but I think the logic could be reviewed.

**Closed** 2022-07-19 08:44 UTC
Labels: needs documentation

**Comment by kolenic-martin** [comment] 2022-07-20 07:25
Hi @vponline, I've run several tests yesterday and so far this works as intended, at least on AWS. There are only a couple more to run, which I should complete later in the morning. I'll keep you posted.

**Comment by kolenic-martin** [comment] 2022-07-20 14:05
I'll give it a spin in the evening and let you know about the results :)

**Comment by kolenic-martin** [comment] 2022-07-20 20:07
Hi @vponline, I can confirm this also results in a successful request fulfillment, so I assume this works as intended :)
