### ISSUE TITLE
Change HTTP Gateway for ChainAPI test calls

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1738] opened 2023-04-12 13:16 UTC
We need to do change HTTP Gateway to make it usable for ChainAPI test API call purposes. The user enters values for each endpoint parameters. e.g. a currency conversion endpoint expects: from, to and amount. The enter these, click execute and the Airnode gateway gets called with these request parameters
The response gets returned to the end user. They can then play with the reserved parameters (if they are user defined) and see the encoded value change in real time. No Airnode/backend calls involved at this point.

The use case:
- Let the user provide the values for the user-defined endpoint parameters
- Call the gateway with these to get the JSON API response
- Let the user provide the values for the reserved parameters and apply them to the JSON at the ChainAPI side to let the user figure things out by trial and error, without requiring additional API calls

Changes to be made:

- Currently the gateway errors if it is called with parameters that would have made a successful API call, but not process it successfully (for example it's missing _type, which is absolutely required to be defined in all requests). For the above to be possible, the gateway needs to respond with the API response JSON and error partially while trying to encode the response.
- The second change is making the reserved parameters inaccessible in pre/post processing to make sure that we can simulate how the reserved parameters will be applied consistently.

Change of the gateway discussion [here](https://api3workspace.slack.com/archives/C02AYRX8D89/p1679587754695669)
Designs on ChainAPI side [here](https://chainapi.slack.com/archives/C02QUC1JY5R/p1680728298771519)

**Comment by bbenligiray** [comment] 2023-07-29 10:51
I have an endpoint with the following reserved parameters
```
"reservedParameters": [
            {
              "name": "_type",
              "fixed": "int256"
            },
            {
              "name": "_path",
              "fixed": "market_data.current_price.usd"
            },
            {
              "name": "_times",
              "fixed": "1000000"
            }
          ]
```
When I call `http-data/` with `{"parameters": {"coinId": "bitcoin"}}`, I get
```
{
    "rawValue": {
        "id": "bitcoin",
        "symbol": "btc",
        "name": "Bitcoin,
        ...
    },
    "encodedValue": "0x00000000000000000000000000000000000000000000000000000006d1c2ac40",
    "values": [
        "29289000000"
    ]
}
```
I update the reserved parameters as below
```
"reservedParameters": [
            {
              "name": "_type"
            }
          ]
```
When I call `http-data/` with {"parameters": {"coinId": "bitcoin"}}, I get
```
{
    "id": "bitcoin",
    "symbol": "btc",
    "name": "Bitcoin",
    ...
}
```
I would have expected
```
{
    "rawValue": {
        "id": "bitcoin",
        "symbol": "btc",
        "name": "Bitcoin,
        ...
    }
}
```

**Comment by bbenligiray** [comment] 2023-07-29 11:49
I created an endpoint with a user-defined `_type`. I added `console.log(input, endpointParameters)` to its pre and post processing. Made http-data, http-signed-data, rrp requests to this endpoint where I specify the `_type` value in `parameters`. The node didn't print `_type` in any of these. I retried the same with Airnode v0.11 and confirmed that the older printed `_type`.
So other than the response schema issue [here](https://github.com/api3dao/airnode/issues/1738#issuecomment-1656703745), this can be considered to be tested.



 provided the `_type` value in the `parameters` of the request, and added `console.log(input, endpointParameters)` to pre and post processing of http-data, http-signed-data, rrp requests

**Comment by bbenligiray** [comment] 2023-07-29 12:05
@andreogle for visibility

**Comment by dcroote** [comment] 2023-07-29 12:37
Well yes this is expected, `_type` is a reserved parameter and:


> We want both pre-processing and post-processing to not have access to the reserved parameters (this seems to only do it for post-processing)

from https://github.com/api3dao/airnode/pull/1831#discussion_r1266899998

**Comment by bbenligiray** [comment] 2023-07-31 08:45
No problems with that, I'm referring to [this](https://github.com/api3dao/airnode/issues/1738#issuecomment-1656703745)

The JSON API response is at the root of the response body or in `rawValue`, depending on if encoding fails. The problem is the user can't tell if the encoding will fail at runtime. This means that while ChainAPI is using `http-data/` to get the raw API response, it will first need to look for a `rawValue` in the response body, and if it doesn't exist, fall back to using the entire body. This is ugly and becomes a more significant issue when the API response has a `rawValue` field at the root level.

**Comment by andreogle** [comment] 2023-07-31 15:53
I'm a bit confused by this. My understanding was that this change was essentially to make expose this `http-data` endpoint as a proxy between ChainAPI and the end API. I would expect this to respond exactly as the end API would respond - after any kind of filtering/transformations are applied. Wrapping everything in a single top level `rawValue` key doesn't make much sense to me.

i.e. I would expect to see this from your example above. 

```json
{
    "id": "bitcoin",
    "symbol": "btc",
    "name": "Bitcoin"
}
```

I'm not following why `encodedValue` and `values` are being returned. They are irrelevant for endpoint testing in ChainAPI

**Comment by bbenligiray** [comment] 2023-08-01 07:08
The only use case for `encodedValue` and `values` for the non-signed gateway is allowing someone like @metobom or a third-party service to test integrations (for example data feed templates wouldn't have any missing reserved parameters) without giving access to any signatures.

**Comment by bbenligiray** [comment] 2023-08-02 11:16
Closing this, the remainder will be tracked by https://github.com/api3dao/airnode/issues/1845

**Closed by bbenligiray** 2023-08-02 11:16 UTC
Labels: needs documentation
