### ISSUE TITLE
Deployment lister displays an unsuccessful deployment

### ISSUE THREAD

**Issue by martinkolenic** [api3dao/airnode#1494] opened 2022-10-06 08:42 UTC
Description: If a deployment fails and a receipt.json is generated (noting that the deployment is unsuccessful), the deployment lister displays it as one of existing deployments. Attempting to remove it then fails, reporting that the deployment does not exist (which is correct).

Steps to reproduce:
1. attempt a deployment and make it so that it fails (maybe disconnect from the internet; my error was that I got a 403 error while attempting to deploy)
2. run the "list" command when deploying
3. attempt to remove the deployment in question (should fail)

Branch: temp-v.0.10.0
System: Fedora 37 beta
Shell: bash

![Image](https://user-images.githubusercontent.com/884979/194262989-779db0bb-c42c-49d5-aaca-54b7fb6e06d0.png)
![Image](https://user-images.githubusercontent.com/884979/194262988-009f7d36-0e13-4af0-a794-e095b4a396e8.png)

**Comment by amarthadan** [comment] 2022-10-07 06:36
This is pretty much a duplicate of https://github.com/api3dao/airnode/issues/1449. The scenario will be tested again when that's done. Closing.

**Closed by amarthadan** 2022-10-07 06:36 UTC
